---
- name: Check if Rust is installed
  ignore_errors: true
  command: rustc --version
  register: rust_check
  environment:
    PATH: "{{ path }}"

- name: Download and run Rust installation script
  when: rust_check.rc != 0
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  environment:
    HOME: "{{ ansible_env.HOME }}"
