---
- name: Install node
  command: "cargo install --locked --path linera-service"
  args:
    chdir: "{{ user_dir }}/daemons/{{ network }}"
  environment:
    PATH: "{{ path }}"
    GOPATH: "{{ user_dir }}/go"

- name: Build Docker container
  command: "docker build -f docker/Dockerfile . -t linera"
  args:
    chdir: "{{ user_dir }}/daemons/linera"
