---
- name: create validator config.toml file
  templates:
    src: "linera.toml.j2"
    dest: "{{ user_dir }}/.{{ network }}/validator.toml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
