---
- name: create validator config.toml file
  templates:
    src: "linera.toml.j2"
    dest: "{{ user_dir }}/.{{ network }}/validator.toml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: copy docker compose file
  copy:
    src: "{{ user_dir }}/daemons/{{ network }}/docker/docker-compose.yml"
    dest: "{{ user_dir }}/.linera/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
