---
- name: make working directory
  file:
    path: "{{ working_dir }}"
    state: directory
    mode: "0755"

- name: copy aleo.sh script
  template:
    src: aleo.sh.j2
    dest: "{{ working_dir }}/aleo.sh"
    mode: 0755
