---
- name: make working directory
  file:
    path: ".{{ network }}"
    state: directory
    mode: "0755"

- name: Handle network specific installation
  include_tasks: "networks/{{ network }}.yml"
